[package]
name = "eternal-vm"
version = "0.1.0"
edition = "2021"

[dependencies]
eternal-account = { version = "0.1.0", path = "../account" }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
