[package]
name = "eternal-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.1"
eternal-vm = { version = "0.1.0", path = "../vm" }
quote = "1.0.28"
syn = "2.0.18"
